# indextank settings
indextank_index: my_index
indextank_api_url: http://:myapikey@myapi.api.indextank.com

# these values are applied as regular expressions 
indextank_excludes: [index.html, 404.html, ^/secret/]